import streamlit as st
from PIL import Image
from streamlit_option_menu import option_menu
st.set_page_config(page_title='Unsur Kimia', page_icon=':🧪:',layout='wide')

#navigasi sidebar
with st.sidebar:
    selected = option_menu('Menu',['Home','Informasi','Unsur Kimia'],
        icons=['house','lamp','heart'], menu_icon='phone', default_index=0)

#halaman home
if (selected == 'Home'):
    image=Image.open('logo.jpeg')
    st.image(image,width=250)
    st.title('Selamat Datang di Aplikasi Unsur Kimia (ɔ◔‿◔)ɔ ♥')
    st.caption(':blue[Tabel periodik kalian hilang? ketinggalan? buka saja APLIKASI UNSUR KIMIA!]')
    st.write('Aplikasi website ini dapat digunakan untuk mengetahui nama unsur, nomor atom, nomor massa, fasa unsur, golongan unsur, titik didih, serta titik leleh dari sebuah unsur kimia')
    st.subheader('Aplikasi ini dibuat dan dikembangkan oleh Kelompok 10 Kelas 1C :')
    st.write('* Amelia Maharani (2219034)')
    st.write('* Dita Suryaningtyas (2219063)')
    st.write('* Firstania Fadhlin Nurhapsari (2219073)')
    st.write('* Silvia Nanda Azzahra (2219166)')
    st.write('* Stevani Juliana Frelin B (2219173)')
#halaman informasi
if (selected == 'Informasi'):
    st.title('Penjelasan Golongan Unsur Kimia 📋')
    st.subheader('Golongan IA (Logam Alkali)')
    st.write('Logam Alkali memiliki 1 elektron valensi yang mudah lepas, sehingga merupakan kelompok logam yang paling reaktif, dapat terbakar di udara, dan bereaksi hebat dengan air.')
    st.subheader('Golongan IIA (Logam Alkali Tanah)')
    st.write('Logam alkali tanah juga tergolong logam aktif, tetapi kereaktifannya kurang dibandingkan dengan logam alkali seperiode, dan hanya akan terbakar di udara bila dipanaskan, kecuali berilium, salah satu logam alkali tanah yang larut dalam air. ')
    st.subheader('Golongan VIIA (Halogen)')
    st.write('Unsur-unsur golongan VIIA merupakan kelompok unsur nonlogam yang sangat reaktif. Hal itu berkaitan dengan elektron valensinya yang berjumlah 7, sehingga hanya memerlukan tambahan 1 elektron untuk mencapai konfigurasi stabil seperti gas mulia. Semua unsur halogen bereaksi dengan tipe yang sama, walaupun kereaktifannya berbeda.Halogen dengan logam membentuk senyawa yang kita sebut garam, seperti NaF, NaCl, NaBr dan NaI. Oleh karena itu pula, unsur golongan VIIA disebut halogen artinya pembentuk garam.')
    st.subheader('Golongan VIIIA (Gas Mulia)')
    st.write('Unsur-unsur golongan VIIIA disebut gas mulia karena semuanya berupa gas yang sangat stabil, sangat sukar bereaksi dengan unsur lain. Tidak ditemukan satu pun senyawa alami dari unsur-unsur tersebut. Unsur gas mulia terdapat di alam sebagai gas monoatomic (atom-atomnya berdiri sendiri).')
       
#halaman unsur kimia
if (selected == 'Unsur Kimia'):
    st.title('UNSUR KIMIA👩🏻‍🔬')
    option=st.selectbox ('Silahkan pilih :blue[unsur kimia yang ingin diketahui]',('','Ac','Ag','Al','Ar','As','Am','At','Au','B','Ba','Be','Bh','Bi','Bk','Br','C','Ca','Cd','Ce','Cf','Cl','Cm','Cn','Co','Cr','Cs','Cu','Db','Ds','Dy','Er','Es','Eu','F','Fe','Fl','Fm','Fr','Ga','Gd','Ge','H','He','Hf','Hg','Ho','Hs','I','In','Ir','K','Kr','La','Li','Lr','Lu','Lv','Mc','Md','Mg','Mn','Mo','Mt','N','Na','Nb','Nd','Ne','Nh','Ni','No','Np','O','Og','Os','P','Pa','Pb','Pd','Pm','Po','Pr','Pt','Pu','Ra','Rb','Re','Rf','Rg','Rh','Rn','Ru','S','Sb','Sc','Se','Sg','Si','Sm','Sn','Sr','Ta','Tb','Tc','Te','Th','Ti','Tl','Tm','Ts','U','V','W','Xe','Y','Yb','Zn','Zr'))
# membuat informasi nama unsur-unsur kimia
    if option == "Ac" :
        st.success ("Nama unsur: Aktinium")
        st.success ("Golongan unsur: IIIB ")
        st.success ("Nomor atom: 89")
        st.success ("Nomor massa: 227 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3471,15 K | 3198 °C | 5788,4 °F")
        st.success ("Titik lebur: 1323,15 K | 1050 °C | 1922 °F")
    elif option == "Ag" :
        st.success ("Nama unsur: Perak")
        st.success ("Golongan unsur: IB ")
        st.success ("Nomor atom: 47 ")
        st.success ("Nomor massa: 108 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 2435,15 K | 2162 °C | 3923,6 °F")
        st.success ("Titik lebur: 1234,93 K | 961,78 °C | 1763,2 °F")
    elif option == "Al" :
        st.success ("Nama unsur: Alumunium ")
        st.success ("Golongan unsur: IIIA ")
        st.success ("Nomor atom: 13  ")
        st.success ("Nomor massa: 27 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 2792,15 K | 2519 °C | 4566,2 °F")
        st.success ("Titik lebur: 933,47 K | 660,32 °C | 1220,58 °F")
    elif option == "Am" :
        st.success ("Nama unsur: Amerisium ")
        st.success ("Golongan unsur: Logam Transisi Dalam ")
        st.success ("Nomor atom: 95 ")
        st.success ("Nomor massa: 243 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 2880,15 K | 2607 °C | 4724,6 °F")
        st.success ("Titik lebur: 1449,15 K | 1176 °C | 2148,8 °F")
    elif option == "Ar" :
        st.success ("Nama unsur: Argon ")
        st.success ("Golongan unsur: VIIIA (Gas Mulia) ")
        st.success ("Nomor atom: 18 ")
        st.success ("Nomor massa: 40 ")
        st.success ("Fasa: Gas")
        st.success ("Titik didih: 87,3 K | -185,85 °C | -302,53 °F")
        st.success ("Titik lebur: 83,8 K | -189,35 °C | -308,83 °F")        
    elif option == "As" :
        st.success ("Nama unsur: Arsen ")
        st.success ("Golongan unsur: VA ")
        st.success ("Nomor atom: 33 ")
        st.success ("Nomor massa: 75 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 876,15 K | 603 °C | 1117,4 °F")
        st.success ("Titik lebur: 1090,15 K | 817 °C | 1502,6 °F")
    elif option == "At" :
        st.success ("Nama unsur: Astatin ")
        st.success ("Golongan unsur: VIIA (Golongan Halogen) ")
        st.success ("Nomor atom: 85  ")
        st.success ("Nomor massa: 210 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 610,15 K | 337 °C | 638,6 °F")
        st.success ("Titik lebur: 575,15 K | 302 °C | 575,6 °F")
    elif option == "Au" :
        st.success ("Nama unsur: Emas ")
        st.success ("Golongan unsur: IB ")
        st.success ("Nomor atom: 79 ")
        st.success ("Nomor massa: 197 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3129,15 K | 2856 °C | 5172,8 °F")
        st.success ("Titik lebur: 1337,35 K | 1064,2 °C | 1947,56 °F")
    elif option == "B" :
        st.success ("Nama unsur: Boron ")
        st.success ("Golongan unsur: IIIA ")
        st.success ("Nomor atom: 5 ")
        st.success ("Nomor massa: 11 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 4200,15 K | 3927 °C | 7100,6 °F")
        st.success ("Titik lebur: 2349,15 K | 2076 °C | 3768,8 °F")
    elif option == "Ba" :
        st.success ("Nama unsur: Barium ")
        st.success ("Golongan unsur: IIA (Alkali Tanah) ")
        st.success ("Nomor atom: 56 ")
        st.success ("Nomor massa: 138 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 2170,15 K | 1897 °C | 3446,6 °F")
        st.success ("Titik lebur: 1000,15 K | 727 °C | 1340,6 °F")
    elif option == "Be" :
        st.success ("Nama unsur: Berilium ")
        st.success ("Golongan unsur: IIA (Alkali Tanah) ")
        st.success ("Nomor atom: 4 ")
        st.success ("Nomor massa: 9 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 2742,15 K | 2469 °C | 4476,2 °F")
        st.success ("Titik lebur: 1560,15 K | 1287 °C | 2348,6 °F")
    elif option == "Bh" :
        st.success ("Nama unsur: Bohrium ")
        st.success ("Golongan unsur: VIIB ")
        st.success ("Nomor atom: 107 ")
        st.success ("Nomor massa: 264 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: -")
        st.success ("Titik lebur: -")
    elif option == "Bi" :
        st.success ("Nama unsur: Bismut ")
        st.success ("Golongan unsur: VA ")
        st.success ("Nomor atom: 83 ")
        st.success ("Nomor massa: 209 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 1837,15 K | 1564 °C | 2847,2 °F")
        st.success ("Titik lebur: 544,65 K | 271,5 °C | 520,7 °F")
    elif option == "Bk" :
        st.success ("Nama unsur: Berkelium ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 97 ")
        st.success ("Nomor massa: 247 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3173,15 K | 2900 °C | 5252 °F")
        st.success ("Titik lebur: 1259,15 K | 986 °C | 1806,8 °F")
    elif option == "Br" :
        st.success ("Nama unsur: Brom ")
        st.success ("Golongan unsur:VIIA (Halogen) ")
        st.success ("Nomor atom: 35 ")
        st.success ("Nomor massa: 80 ")
        st.success ("Fasa: Liquid")
        st.success ("Titik didih: 331,95 K | 58,8 °C | 137,84 °F")
        st.success ("Titik lebur: 265,95 K | -7,2 °C | 19,04 °F")
    elif option == "C" :
        st.success ("Nama unsur: Karbon ")
        st.success ("Golongan unsur: IVA ")
        st.success ("Nomor atom: 6 ")
        st.success ("Nomor massa: 12 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 4300,15 K | 4027 °C | 7280,6 °F")
        st.success ("Titik lebur: 3948,15 K | 3675 °C | 6647 °F")
    elif option == "Ca" :
        st.success ("Nama unsur: Kalsium ")
        st.success ("Golongan unsur: IIA ")
        st.success ("Nomor atom: 20 ")
        st.success ("Nomor massa: 40 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 1757,15 K | 1484 °C | 2703,2 °F")
        st.success ("Titik lebur: 1115,15 K | 842 °C | 1547,6 °F")
    elif option == "Cd" :
        st.success ("Nama unsur: Kadmium ")
        st.success ("Golongan unsur: IIB ")
        st.success ("Nomor atom: 48 ")
        st.success ("Nomor massa: 112 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 1040,15 K | 767 °C | 1412,6 °F")
        st.success ("Titik lebur: 594,22 K | 321,07 °C | 609,93 °F")
    elif option == "Ce" :
        st.success ("Nama unsur: Serium ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 58 ")
        st.success ("Nomor massa: 140 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3716,15 K | 3443 °C | 6229,4 °F")
        st.success ("Titik lebur: 1068,15 K | 795 °C | 1463 °F")
    elif option == "Cf" :
        st.success ("Nama unsur: Kalifornium ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 98 ")
        st.success ("Nomor massa: 251 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: -")
        st.success ("Titik lebur: 1173,15 K | 900 °C | 1652 °F")
    elif option == "Cl" :
        st.success ("Nama unsur: Klor ")
        st.success ("Golongan unsur: VIIA (Halogen) ")
        st.success ("Nomor atom: 17 ")
        st.success ("Nomor massa: 35 ")
        st.success ("Fasa: Gas")
        st.success ("Titik didih: 239,11 K | -34,04 °C | -29,27 °F")
        st.success ("Titik lebur: 171,65 K | -101,5 °C | -150,7 °F")
    elif option == "Cm" :
        st.success ("Nama unsur: Curium ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 96 ")
        st.success ("Nomor massa: 247 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3383,15 K | 3110 °C | 5630 °F")
        st.success ("Titik lebur: 1613,15 K | 1340 °C | 2444 °F")
    elif option == "Cn" :
        st.success ("Nama unsur: Kopernisium ")
        st.success ("Golongan unsur: IIB ")
        st.success ("Nomor atom: 112 ")
        st.success ("Nomor massa: 285 ")
        st.success ("Fasa: Liquid")
        st.success ("Titik didih: -")
        st.success ("Titik lebur: -")
    elif option == "Co" :
        st.success ("Nama unsur: Kobalt ")
        st.success ("Golongan unsur: VIIIB ") 
        st.success ("Nomor atom: 27 ")
        st.success ("Nomor massa: 59 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3200,15 K | 2927 °C | 5300,6 °F")
        st.success ("Titik lebur: 1768,15 K | 1495 °C | 2723 °F")
    elif option == "Cr" :
        st.success ("Nama unsur: Krom ")
        st.success ("Golongan unsur: VIB ")
        st.success ("Nomor atom: 24 ") 
        st.success ("Nomor massa: 52 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 2944,15 K | 2671 °C | 4839,8 °F")
        st.success ("Titik lebur: 2180,15 K | 1907 °C | 3464,6 °F")
    elif option == "Cs" :
        st.success ("Nama unsur: Sesium ")
        st.success ("Golongan unsur: IA ")
        st.success ("Nomor atom: 55 ")
        st.success ("Nomor massa: 133 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 944,15 K | 671 °C | 1239,8 °F")
        st.success ("Titik lebur: 301,59 K | 28,44 °C | 83,19 °F")
    elif option == "Cu" :
        st.success ("Nama unsur: Tembaga ")
        st.success ("Golongan unsur: IB ")
        st.success ("Nomor atom: 29 ")
        st.success ("Nomor massa: 64 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 2835,15 K | 2562 °C | 4643,6 °F")
        st.success ("Titik lebur: 1357,75 K | 1084,6 °C | 1984,28 °F")
    elif option == "Db" :
        st.success ("Nama unsur: Dubnium ")
        st.success ("Golongan unsur: VB ")
        st.success ("Nomor atom: 105 ")
        st.success ("Nomor massa: 262 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: -")
        st.success ("Titik lebur: -")
    elif option == "Ds" :
        st.success ("Nama unsur: Darmstadtium ")
        st.success ("Golongan unsur: VIIIB ")
        st.success ("Nomor atom: 110 ")
        st.success ("Nomor massa: 281 ")
        st.success ("Fasa: Tidak diketahui")
        st.success ("Titik didih: -")
        st.success ("Titik lebur: -")       
    elif option == "Dy" :
        st.success ("Nama unsur: Disprosium ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 66 ")
        st.success ("Nomor massa: 163 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 2840,15 K | 2567 °C | 4652,6 °F")
        st.success ("Titik lebur: 1680,15 K | 1407 °C | 2564,6 °F")                                                                    
    elif option == "Er" :
        st.success ("Nama unsur: Erbium ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 68 ")
        st.success ("Nomor massa: 167 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3141,15 K | 2868 °C | 5194,4 °F")
        st.success ("Titik lebur: 1802,15 K | 1529 °C | 2784,2 °F")  
    elif option == "Es" :
        st.success ("Nama unsur: Einsteinium ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 99 ")
        st.success ("Nomor massa: 252 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: -")
        st.success ("Titik lebur: 1133,15 K | 860 °C | 1580 °F")  
    elif option == "Eu" :
        st.success ("Nama unsur: Europium ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 63 ")
        st.success ("Nomor massa: 152 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 1802,15 K | 1529 °C | 2784,2 °F")
        st.success ("Titik lebur: 1099,15 K | 826 °C | 1518,8 °F")  
    elif option == "F" :
        st.success ("Nama unsur: Fluor ")
        st.success ("Golongan unsur: VIIA (Halogen) ")
        st.success ("Nomor atom: 9 ")
        st.success ("Nomor massa: 19 ")
        st.success ("Fasa: Gas")
        st.success ("Titik didih: 85,03 K | -188,12 °C | -306,62 °F")
        st.success ("Titik lebur: 53,53 K | -219,62 °C | -363,32 °F")  
    elif option == "Fe" :
        st.success ("Nama unsur: Besi  ")
        st.success ("Golongan unsur: VIIIB ")
        st.success ("Nomor atom: 26 ")
        st.success ("Nomor massa: 56 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3134,15 K | 2861 °C | 5181,8 °F")
        st.success ("Titik lebur: 1811,15 K | 1538 °C | 2800,4 °F")
    elif option == "Fl" :
        st.success ("Nama unsur: Flerovium ")
        st.success ("Golongan unsur: IV A ")
        st.success ("Nomor atom: 114 ")
        st.success ("Nomor massa: 287 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 423,15 K | 150 °C | 302 °F")
        st.success ("Titik lebur: 343,15 K | 70 °C | 158 °F")  
    elif option == "Fm" :
        st.success ("Nama unsur: Fermium ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 100 ")
        st.success ("Nomor massa: 257 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: -")
        st.success ("Titik lebur: 1800,15 K | 1527 °C | 2780,6 °F")               
    elif option == "Fr" :
        st.success ("Nama unsur: Fransium  ")
        st.success ("Golongan unsur: IA ")
        st.success ("Nomor atom: 87 ")
        st.success ("Nomor massa: 223 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 950,15 K | 677 °C | 1250,6 °F")
        st.success ("Titik lebur: 296,15 K | 23 °C | 73,4 °F")                 
    elif option == "Ga" :
        st.success ("Nama unsur: Galium ")
        st.success ("Golongan unsur: IIIA ")
        st.success ("Nomor atom: 31 ")
        st.success ("Nomor massa: 70 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 2477,15 K | 2204 °C | 3999,2 °F")
        st.success ("Titik lebur: 302,91 K | 29,76 °C | 85,57 °F")              
    elif option == "Gd" :
        st.success ("Nama unsur: Gadolinium ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 64 ")
        st.success ("Nomor massa: 157 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3546,15 K | 3273 °C | 5923,4 °F")
        st.success ("Titik lebur: 1585,15 K | 1312 °C | 2393,6 °F")               
    elif option == "Ge" :
        st.success ("Nama unsur: Germanium ")
        st.success ("Golongan unsur: IVA ")
        st.success ("Nomor atom: 32 ")
        st.success ("Nomor massa: 73 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3106,15 K | 2833 °C | 5131,4 °F")
        st.success ("Titik lebur: 1211,4 K | 938,25 °C | 1720,85 °F")         
    elif option == "H" :
        st.success ("Nama unsur: Hidrogen ")
        st.success ("Golongan unsur: IA ")
        st.success ("Nomor atom: 1 ")
        st.success ("Nomor massa: 1 ")
        st.success ("Fasa: Gas")
        st.success ("Titik didih:20,28 K | -252,87 °C | -423,17 °F")
        st.success ("Titik lebur: 14,01 K | -259,14 °C | -434,45 °F")         
    elif option == "He" :
        st.success ("Nama unsur: Helium ")
        st.success ("Golongan unsur: VIIIA (Gas Mulia) ")
        st.success ("Nomor atom: 2 ")
        st.success ("Nomor massa: 4 ")
        st.success ("Fasa: Gas")
        st.success ("Titik didih: 4,22 K | -268,93 °C | -452,07 °F")
        st.success ("Titik lebur: 0,95 K | -272,2 °C | -457,96 °F")         
    elif option == "Hf" :
        st.success ("Nama unsur:Hafnium ")
        st.success ("Golongan unsur: IVB ")
        st.success ("Nomor atom: 72 ")
        st.success ("Nomor massa: 178 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 4876,15 K | 4603 °C | 8317,4 °F")
        st.success ("Titik lebur: 2506,15 K | 2233 °C | 4051,4 °F")         
    elif option == "Hg" :
        st.success ("Nama unsur: Raksa ")
        st.success ("Golongan unsur: IIB ")
        st.success ("Nomor atom: 80 ")
        st.success ("Nomor massa: 201 ")
        st.success ("Fasa: Liquid")
        st.success ("Titik didih: 630,15 K | 357 °C | 674,6 °F")
        st.success ("Titik lebur: 234,32 K | -38,83 °C | -37,89 °F")             
    elif option == "Ho" :
        st.success ("Nama unsur: Holmium ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 67 ")
        st.success ("Nomor massa: 165 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 2993,15 K | 2720 °C | 4928 °F")
        st.success ("Titik lebur: 1734,15 K | 1461 °C | 2661,8 °F") 
    elif option == "Hs" :
        st.success ("Nama unsur: Hassium ")
        st.success ("Golongan unsur: VIIIB ")
        st.success ("Nomor atom: 108 ")
        st.success ("Nomor massa: 269 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: -")
        st.success ("Titik lebur: -") 
    elif option == "I" :
        st.success ("Nama unsur: Yodium ")
        st.success ("Golongan unsur: VIIA (Halogen) ")
        st.success ("Nomor atom: 53 ")
        st.success ("Nomor massa: 127 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 457,4 K | 184,25 °C | 363,65 °F")
        st.success ("Titik lebur: 386,85 K | 113,7 °C | 236,66 °F") 
    elif option == "In" :
        st.success ("Nama unsur: Indium ")
        st.success ("Golongan unsur: IIIA ")
        st.success ("Nomor atom: 49 ")
        st.success ("Nomor massa: 115 ")
        st.success ("Fasa: Solid ")
        st.success ("Titik didih: 2345,15 K | 2072 °C | 3761,6 °F ")
        st.success ("Titik lebur: 429,75 K | 156,6 °C | 313,88 °F ") 
    elif option == "Ir" :
        st.success ("Nama unsur: Iridium ")
        st.success ("Golongan unsur: VIIIB ")
        st.success ("Nomor atom: 77 ")
        st.success ("Nomor massa: 192 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 2345,15 K | 2072 °C | 3761,6 °F")
        st.success ("Titik lebur: 429,75 K | 156,6 °C | 313,88 °F") 
    elif option == "K" :
        st.success ("Nama unsur: Kalium ")
        st.success ("Golongan unsur: IA ")
        st.success ("Nomor atom: 19 ")
        st.success ("Nomor massa: 39 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 1032,15 K | 759 °C | 1398,2 °F")
        st.success ("Titik lebur: 336,53 K | 63,38 °C | 146,08 °F") 
    elif option == "Kr" :
        st.success ("Nama unsur: Kripton ")
        st.success ("Golongan unsur: VIIIA (Gas Mulia) ")
        st.success ("Nomor atom: 36 ")
        st.success ("Nomor massa: 84 ")
        st.success ("Fasa: Gas")
        st.success ("Titik didih: 119,93 K | -153,22 °C | -243,8 °F")
        st.success ("Titik lebur: 115,79 K | -157,36 °C | -251,25 °F") 
    elif option == "La" :
        st.success ("Nama unsur: Lantanum ")
        st.success ("Golongan unsur: IIIB ")
        st.success ("Nomor atom: 57 ")
        st.success ("Nomor massa: 139 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3737,15 K | 3464 °C | 6267,2 °F")
        st.success ("Titik lebur: 1193,15 K | 920 °C | 1688 °F") 
    elif option == "Li" :
        st.success ("Nama unsur: Litium ")
        st.success ("Golongan unsur: IA ")
        st.success ("Nomor atom: 3 ")
        st.success ("Nomor massa: 7 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 1615,15 K | 1342 °C | 2447,6 °F")
        st.success ("Titik lebur: 453,69 K | 180,54 °C | 356,97 °F")
    elif option == "Lr" :
        st.success ("Nama unsur: Lawrensium ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 103 ")
        st.success ("Nomor massa: 262 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: -")
        st.success ("Titik lebur: 1900 K | 1626,85 °C | 2960,33 °F")
    elif option == "Lu" :
        st.success ("Nama unsur: Lutetium ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 71 ")
        st.success ("Nomor massa: 175 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3675,15 K | 3402 °C | 6155,6 °F")
        st.success ("Titik lebur: 1925,15 K | 1652 °C | 3005,6 °F")
    elif option == "Lv" :
        st.success ("Nama unsur: Livermorium ")
        st.success ("Golongan unsur: VIA ")
        st.success ("Nomor atom: 116 ")
        st.success ("Nomor massa: 291 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: -")
        st.success ("Titik lebur: -")
    elif option == "Mc" :
        st.success ("Nama unsur: Moskovium ")
        st.success ("Golongan unsur: VA ")
        st.success ("Nomor atom: 115 ")
        st.success ("Nomor massa: 288 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: -")
        st.success ("Titik lebur: -")
    elif option == "Md" :
        st.success ("Nama unsur: Mendelevium ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 101 ")
        st.success ("Nomor massa: 258 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: -")
        st.success ("Titik lebur: 1100 K | 826,85 °C | 1520,33 °F")
    elif option == "Mg" :
        st.success ("Nama unsur: Magnesium ")
        st.success ("Golongan unsur: IIA (Logam Alkali Tanah) ")
        st.success ("Nomor atom: 12 ")
        st.success ("Nomor massa: 24 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 1363,15 K | 1090 °C | 1994 °F")
        st.success ("Titik lebur: 923,15 K | 650 °C | 1202 °F")        
    elif option == "Mn" :
        st.success ("Nama unsur: Mangan ")
        st.success ("Golongan unsur: VIIB ")
        st.success ("Nomor atom: 25 ")
        st.success ("Nomor massa: 55 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 2334,15 K | 2061 °C | 3741,8 °F")
        st.success ("Titik lebur: 1519,15 K | 1246 °C | 2274,8 °F")        
    elif option == "Mo" :
        st.success ("Nama unsur: Molibden ")
        st.success ("Golongan unsur: VIB ")
        st.success ("Nomor atom: 42 ")
        st.success ("Nomor massa: 96 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 4912,15 K | 4639 °C | 8382,2 °F")
        st.success ("Titik lebur: 2896,15 K | 2623 °C | 4753,4 °F")        
    elif option == "Mt" :
        st.success ("Nama unsur: Meitnerium ")
        st.success ("Golongan unsur: VIIIB ")
        st.success ("Nomor atom: 109 ")
        st.success ("Nomor massa: 268 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: -")
        st.success ("Titik lebur: -")         
    elif option == "N" :
        st.success ("Nama unsur: Nitrogen ")
        st.success ("Golongan unsur: VA ")
        st.success ("Nomor atom: 7 ")
        st.success ("Nomor massa: 14 ")
        st.success ("Fasa: Gas")
        st.success ("Titik didih: 77,36 K | -195,79 °C | -320,42 °F")
        st.success ("Titik lebur: 63,15 K | -210 °C | -346 °F")        
    elif option == "Na" :
        st.success ("Nama unsur: Natrium ")
        st.success ("Golongan unsur: IA ")
        st.success ("Nomor atom: 11 ")
        st.success ("Nomor massa: 23 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 1156,15 K | 883 °C | 1621,4 °F")
        st.success ("Titik lebur: 370,87 K | 97,72 °C | 207,9 °F")          
    elif option == "Nb" :
        st.success ("Nama unsur: Niobium ")
        st.success ("Golongan unsur: VB ")
        st.success ("Nomor atom: 41 ")
        st.success ("Nomor massa: 93 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 5017,15 K | 4744 °C | 8571,2 °F")
        st.success ("Titik lebur: 2750,15 K | 2477 °C | 4490,6 °F")          
    elif option == "Nd" :
        st.success ("Nama unsur: Neodimium ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 60 ")
        st.success ("Nomor massa: 144 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3347,15 K | 3074 °C | 5565,2 °F")
        st.success ("Titik lebur: 1297,15 K | 1024 °C | 1875,2 °F")  
    elif option == "Ne" :
        st.success ("Nama unsur: Neon ")
        st.success ("Golongan unsur: VIIIA (Gas Mulia) ")
        st.success ("Nomor atom: 10 ")
        st.success ("Nomor massa: 20 ")
        st.success ("Fasa: Gas")
        st.success ("Titik didih: 27,07 K | -246,08 °C | -410,94 °F")
        st.success ("Titik lebur: 24,56 K | -248,59 °C | -415,46 °F")             
    elif option == "Nh" :
        st.success ("Nama unsur: Nihonium ")
        st.success ("Golongan unsur: IIIA ")
        st.success ("Nomor atom: 113 ")
        st.success ("Nomor massa: 286 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 1373,15 K | 1100 °C | 2012 °F")
        st.success ("Titik lebur: 703,15 K | 430 °C | 806 °F")          
    elif option == "Ni" :
        st.success ("Nama unsur: Nikel ")
        st.success ("Golongan unsur: VIIIB ")
        st.success ("Nomor atom: 28 ")
        st.success ("Nomor massa: 59 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3186,15 K | 2913 °C | 5275,4 °F")
        st.success ("Titik lebur: 1728,15 K | 1455 °C | 2651 °F")          
    elif option == "No" :
        st.success ("Nama unsur: Nobelium ")
        st.success ("Golongan unsur: (Logam Transisi Logam) ")
        st.success ("Nomor atom: 102 ")
        st.success ("Nomor massa: 259 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: -")
        st.success ("Titik lebur: 1100,15 K | 827 °C | 1520,6 °F")          
    elif option == "Np" :
        st.success ("Nama unsur: Neptunium ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 93 ")
        st.success ("Nomor massa: 237 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 4273,15 K | 4000 °C | 7232 °F")
        st.success ("Titik lebur: 910,15 K | 637 °C | 1178,6 °F")         
    elif option == "O" :
        st.success ("Nama unsur: Oksigen ")
        st.success ("Golongan unsur: VIA ")
        st.success ("Nomor atom: 8 ")
        st.success ("Nomor massa: 16 ")
        st.success ("Fasa: Gas")
        st.success ("Titik didih: 90,2 K | -182,95 °C | -297,31 °F")
        st.success ("Titik lebur: 54,36 K | -218,79 °C | -361,82 °F")          
    elif option == "Og" :
        st.success ("Nama unsur: Oganeson ")
        st.success ("Golongan unsur: VIIIA ")
        st.success ("Nomor atom: 118 ")
        st.success ("Nomor massa: 294 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: -")
        st.success ("Titik lebur: -")        
    elif option == "Os" :
        st.success ("Nama unsur: Osmium ")
        st.success ("Golongan unsur: VIIIB ")
        st.success ("Nomor atom: 76 ")
        st.success ("Nomor massa: 190 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 5285,15 K | 5012 °C | 9053,6 °F")
        st.success ("Titik lebur: 3306,15 K | 3033 °C | 5491,4 °F")        
    elif option == "P" :
        st.success ("Nama unsur: Fosfor ")
        st.success ("Golongan unsur: VA ")
        st.success ("Nomor atom: 15 ")
        st.success ("Nomor massa: 31 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 553 K | 279,85 °C | 535,73 °F")
        st.success ("Titik lebur: 317,25 K | 44,1 °C | 111,38 °F")             
    elif option == "Pa" :
        st.success ("Nama unsur: Protaktinium ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 91 ")
        st.success ("Nomor massa: 231 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 4300,15 K | 4027 °C | 7280,6 °F")
        st.success ("Titik lebur: 1841,15 K | 1568 °C | 2854,4 °F")             
    elif option == "Pb" :
        st.success ("Nama unsur: Timbal  ")
        st.success ("Golongan unsur: IVA ")
        st.success ("Nomor atom: 82 ")
        st.success ("Nomor massa: 207 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 2022,15 K | 1749 °C | 3180,2 °F")
        st.success ("Titik lebur: 600,61 K | 327,46 °C | 621,43 °F")             
    elif option == "Pd" :
        st.success ("Nama unsur: Paladium ")
        st.success ("Golongan unsur: VIIIB ")
        st.success ("Nomor atom: 46 ")
        st.success ("Nomor massa: 106 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3236,15 K | 2963 °C | 5365,4 °F")
        st.success ("Titik lebur: 1828,05 K | 1554,9 °C | 2830,82 °F")           
    elif option == "Pm" :
        st.success ("Nama unsur: Prometium ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 61 ")
        st.success ("Nomor massa: 145 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3273,15 K | 3000 °C | 5432 °F")
        st.success ("Titik lebur: 1315,15 K | 1042 °C | 1907,6 °F")             
    elif option == "Po" :
        st.success ("Nama unsur: Polonium ")
        st.success ("Golongan unsur: VIA ")
        st.success ("Nomor atom: 84 ")
        st.success ("Nomor massa: 210 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 1235,15 K | 962 °C | 1763,6 °F")
        st.success ("Titik lebur: 527,15 K | 254 °C | 489,2 °F")             
    elif option == "Pr" :
        st.success ("Nama unsur: Praseodimium ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 59 ")
        st.success ("Nomor massa: 141 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3793,15 K | 3520 °C | 6368 °F")
        st.success ("Titik lebur: 1208,15 K | 935 °C | 1715 °F")             
    elif option == "Pt" :
        st.success ("Nama unsur: Platina  ")
        st.success ("Golongan unsur: VIIIB ")
        st.success ("Nomor atom: 78 ")
        st.success ("Nomor massa: 195 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 4098,15 K | 3825 °C | 6917 °F")
        st.success ("Titik lebur: 2041,45 K | 1768,3 °C | 3214,94 °F")           
    elif option == "Pu" :
        st.success ("Nama unsur: Plutonium ")
        st.success ("Golongan unsur:  (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 94 ")
        st.success ("Nomor massa: 244 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3501,15 K | 3228 °C | 5842,4 °F")
        st.success ("Titik lebur: 912,55 K | 639,4 °C | 1182,92 °F")             
    elif option == "Ra" :
        st.success ("Nama unsur: Radium ")
        st.success ("Golongan unsur: IIA (Logam Alkali Tanah) ")
        st.success ("Nomor atom: 88 ")
        st.success ("Nomor massa: 226 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 2010,15 K | 1737 °C | 3158,6 °F")
        st.success ("Titik lebur: 973,15 K | 700 °C | 1292 °F")             
    elif option == "Rb" :
        st.success ("Nama unsur: Rubidium ")
        st.success ("Golongan unsur: IB ")
        st.success ("Nomor atom: 37 ")
        st.success ("Nomor massa: 85 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 961,15 K | 688 °C | 1270,4 °F")
        st.success ("Titik lebur: 312,46 K | 39,31 °C | 102,76 °F")               
    elif option == "Re" :
        st.success ("Nama unsur: Renium ")
        st.success ("Golongan unsur: VIIB ")
        st.success ("Nomor atom: 75 ")
        st.success ("Nomor massa: 186 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 5869,15 K | 5596 °C | 10104,8 °F")
        st.success ("Titik lebur: 3459,15 K | 3186 °C | 5766,8 °F")        
    elif option == "Rf" :
        st.success ("Nama unsur: Rutherfordium ")
        st.success ("Golongan unsur: IVB ")
        st.success ("Nomor atom: 104 ")
        st.success ("Nomor massa: 261 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 5773,15 K | 5500 °C | 9932 °F")
        st.success ("Titik lebur: 2373,15 K | 2100 °C | 3812 °F")        
    elif option == "Rg" :
        st.success ("Nama unsur: Roentgenium ")
        st.success ("Golongan unsur: IB ")
        st.success ("Nomor atom: 111 ")
        st.success ("Nomor massa: 281 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: -")
        st.success ("Titik lebur: -")        
    elif option == "Rh" :
        st.success ("Nama unsur: Rodium ")
        st.success ("Golongan unsur: VIIIB ")
        st.success ("Nomor atom: 45 ")
        st.success ("Nomor massa: 103 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3968,15 K | 3695 °C | 6683 °F")
        st.success ("Titik lebur: 2237,15 K | 1964 °C | 3567,2 °F")        
    elif option == "Rn" :
        st.success ("Nama unsur: Radon ")
        st.success ("Golongan unsur: VIIIA (Gas Mulia) ")
        st.success ("Nomor atom: 86 ")
        st.success ("Nomor massa: 222 ")
        st.success ("Fasa: Gas")
        st.success ("Titik didih: 211,3 K | -61,85 °C | -79,33 °F")
        st.success ("Titik lebur: 202 K | -71,15 °C | -96,07 °F")        
    elif option == "Ru" :
        st.success ("Nama unsur: Ruthenium ")
        st.success ("Golongan unsur: VIIIB ")
        st.success ("Nomor atom: 44 ")
        st.success ("Nomor massa: 101 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 4423,15 K | 4150 °C | 7502 °F")
        st.success ("Titik lebur: 2607,15 K | 2334 °C | 4233,2 °F")            
    elif option == "S" :
        st.success ("Nama unsur: Belerang ")
        st.success ("Golongan unsur: VIA ")
        st.success ("Nomor atom: 16 ")
        st.success ("Nomor massa: 32 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 717,8 K | 444,65 °C | 832,37 °F")
        st.success ("Titik lebur: 388,36 K | 115,21 °C | 239,38 °F")            
    elif option == "Sb" :
        st.success ("Nama unsur: Antimon ")
        st.success ("Golongan unsur: VA ")
        st.success ("Nomor atom: 51 ")
        st.success ("Nomor massa: 122 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 1860,15 K | 1587 °C | 2888,6 °F")
        st.success ("Titik lebur: 903,78 K | 630,63 °C | 1167,13 °F")            
    elif option == "Sc" :
        st.success ("Nama unsur: Skandium  ")
        st.success ("Golongan unsur: IIIB ")
        st.success ("Nomor atom: 21 ")
        st.success ("Nomor massa: 45 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3109,15 K | 2836 °C | 5136,8 °F")
        st.success ("Titik lebur: 1814,15 K | 1541 °C | 2805,8 °F")            
    elif option == "Se" :
        st.success ("Nama unsur: Selenium ")
        st.success ("Golongan unsur: VIA ")
        st.success ("Nomor atom: 34 ")
        st.success ("Nomor massa: 79 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 958,15 K | 685 °C | 1265 °F")
        st.success ("Titik lebur: 494,15 K | 221 °C | 429,8 °F")            
    elif option == "Sg" :
        st.success ("Nama unsur: Seaborgium ")
        st.success ("Golongan unsur: VIB ")
        st.success ("Nomor atom: 106 ")
        st.success ("Nomor massa: 262 ")
        st.success ("Fasa: Solid ")
        st.success ("Titik didih: -")
        st.success ("Titik lebur: -")            
    elif option == "Si" :
        st.success ("Nama unsur: Silikon ")
        st.success ("Golongan unsur: IVA ")
        st.success ("Nomor atom: 14 ")
        st.success ("Nomor massa: 28 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3538,15 K | 3265 °C | 5909 °F")
        st.success ("Titik lebur: 1687,15 K | 1414 °C | 2577,2 °F")            
    elif option == "Sm" :
        st.success ("Nama unsur: Samarium  ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 62 ")
        st.success ("Nomor massa: 150 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 2067,15 K | 1794 °C | 3261,2 °F")
        st.success ("Titik lebur: 1345,15 K | 1072 °C | 1961,6 °F")            
    elif option == "Sn" :
        st.success ("Nama unsur: Timah ")
        st.success ("Golongan unsur: IVA ")
        st.success ("Nomor atom: 50 ")
        st.success ("Nomor massa: 119 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 2875,15 K | 2602 °C | 4715,6 °F")
        st.success ("Titik lebur: 505,08 K | 231,93 °C | 449,47 °F")    
    elif option == "Sr" :
        st.success ("Nama unsur: Strontium ")
        st.success ("Golongan unsur: IIA (Logam Alkali Tanah) ")
        st.success ("Nomor atom: 38 ")
        st.success ("Nomor massa: 88 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 1655,15 K | 1382 °C | 2519,6 °F")
        st.success ("Titik lebur: 1050,15 K | 777 °C | 1430,6 °F")            
    elif option == "Ta" :
        st.success ("Nama unsur: Tantalum ")
        st.success ("Golongan unsur: VA ")
        st.success ("Nomor atom: 73 ")
        st.success ("Nomor massa: 181 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 5731,15 K | 5458 °C | 9856,4 °F")
        st.success ("Titik lebur: 3290,15 K | 3017 °C | 5462,6 °F")            
    elif option == "Tb" :
        st.success ("Nama unsur: Terbium ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 65 ")
        st.success ("Nomor massa: 159 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3503,15 K | 3230 °C | 5846 °F")
        st.success ("Titik lebur: 1629,15 K | 1356 °C | 2472,8 °F")        
    elif option == "Tc" :
        st.success ("Nama unsur: Teknetium ")
        st.success ("Golongan unsur: VIIB ")
        st.success ("Nomor atom: 43 ")
        st.success ("Nomor massa: 98 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 4538,15 K | 4265 °C | 7709 °F")
        st.success ("Titik lebur: 2430,15 K | 2157 °C | 3914,6 °F")        
    elif option == "Te" :
        st.success ("Nama unsur: Telurium ")
        st.success ("Golongan unsur: VIA ")
        st.success ("Nomor atom: 52 ")
        st.success ("Nomor massa: 128 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 1261,15 K | 988 °C | 1810,4 °F")
        st.success ("Titik lebur: 722,66 K | 449,51 °C | 841,12 °F")        
    elif option == "Th" :
        st.success ("Nama unsur: Torium ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 90 ")
        st.success ("Nomor massa: 232 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 5061,15 K | 4788 °C | 8650,4 °F")
        st.success ("Titik lebur: 2115,15 K | 1842 °C | 3347,6 °F")        
    elif option == "Ti" :
        st.success ("Nama unsur: Titanium ")
        st.success ("Golongan unsur: IVB ")
        st.success ("Nomor atom: 22 ")
        st.success ("Nomor massa: 48 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3560,15 K | 3287 °C | 5948,6 °F")
        st.success ("Titik lebur: 1941,15 K | 1668 °C | 3034,4 °F")        
    elif option == "Tl" :
        st.success ("Nama unsur: Talium ")
        st.success ("Golongan unsur: IIIA  ")
        st.success ("Nomor atom: 81 ")
        st.success ("Nomor massa: 204 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 1746,15 K | 1473 °C | 2683,4 °F")
        st.success ("Titik lebur: 577,15 K | 304 °C | 579,2 °F")        
    elif option == "Tm" :
        st.success ("Nama unsur: Tulium  ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 69 ")
        st.success ("Nomor massa: 169 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 2223,15 K | 1950 °C | 3542 °F")
        st.success ("Titik lebur: 1818,15 K | 1545 °C | 2813 °F")        
    elif option == "Ts" :
        st.success ("Nama unsur: Tenesin ")
        st.success ("Golongan unsur: VIIA ")
        st.success ("Nomor atom: 117 ")
        st.success ("Nomor massa: 294 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: -")
        st.success ("Titik lebur: -")        
    elif option == "U" :
        st.success ("Nama unsur: Uranium ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 92 ")
        st.success ("Nomor massa: 238 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 4404,15 K | 4131 °C | 7467,8 °F")
        st.success ("Titik lebur: 1405,35 K | 1132,2 °C | 2069,96 °F")        
    elif option == "V" :
        st.success ("Nama unsur: Vanadium ")
        st.success ("Golongan unsur: VB ")
        st.success ("Nomor atom: 23 ")
        st.success ("Nomor massa: 51 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3680,15 K | 3407 °C | 6164,6 °F")
        st.success ("Titik lebur: 2183,15 K | 1910 °C | 3470 °F")
    elif option == "W" :
        st.success ("Nama unsur: Tungsten ")
        st.success ("Golongan unsur: VIB ")
        st.success ("Nomor atom: 74 ")
        st.success ("Nomor massa: 184 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 5828,15 K | 5555 °C | 10031 °F")
        st.success ("Titik lebur: 3695,15 K | 3422 °C | 6191,6 °F")
    elif option == "Xe" :
        st.success ("Nama unsur: Xenon ")
        st.success ("Golongan unsur: VIIIA (Gas Mulia) ")
        st.success ("Nomor atom: 54 ")
        st.success ("Nomor massa: 131 ")
        st.success ("Fasa: Gas")
        st.success ("Titik didih: 165,03 K | -108,12 °C | -162,62 °F")
        st.success ("Titik lebur: 161,45 K | -111,7 °C | -169,06 °F")        
    elif option == "Y" :
        st.success ("Nama unsur:  Itrium ")
        st.success ("Golongan unsur: IIIB ")
        st.success ("Nomor atom: 39 ")
        st.success ("Nomor massa: 89 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 3609,15 K | 3336 °C | 6036,8 °F")
        st.success ("Titik lebur: 1799,15 K | 1526 °C | 2778,8 °F")        
    elif option == "Yb" :
        st.success ("Nama unsur:  Iterbium ")
        st.success ("Golongan unsur: (Logam Transisi Dalam) ")
        st.success ("Nomor atom: 70 ")
        st.success ("Nomor massa: 173 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 1469,15 K | 1196 °C | 2184,8 °F")
        st.success ("Titik lebur: 1097,15 K | 824 °C | 1515,2 °F")        
    elif option == "Zn" :
        st.success ("Nama unsur: Seng ")
        st.success ("Golongan unsur: IIB ")
        st.success ("Nomor atom: 30 ")
        st.success ("Nomor massa: 65 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 1180,15 K | 907 °C | 1664,6 °F")
        st.success ("Titik lebur: 692,68 K | 419,53 °C | 787,15 °F")        
    elif option == "Zr" :
        st.success ("Nama unsur: Zirkonium ")
        st.success ("Golongan unsur: IVB ")
        st.success ("Nomor atom: 40 ")
        st.success ("Nomor massa: 91 ")
        st.success ("Fasa: Solid")
        st.success ("Titik didih: 4682,15 K | 4409 °C | 7968,2 °F")
        st.success ("Titik lebur: 2128,15 K | 1855 °C | 3371 °F")        
                            
                      
         





